server:
  port: 8080
  tomcat:
    max-http-form-post-size: -1

spring:
  profiles:
    active: dev #prod test
  application:
    name: pokerjh
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/poker
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 150
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 50MB

upload:
  savePath: /htcdc/projectTest/upload
  baseUrl: http://192.168.31.17:8081


logging:
  level:
    com:
      github: debug
    org:
      nutz: debug